name: CI - Web y API

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:

  api-tests:
    name: API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas API
        run: npm run test:api -- --json --outputFile=api-report.json

      - name: Subir reporte API
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: api-test-report
          path: api-report.json

  web-tests:
    name: Web Tests
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Instalar dependencias
        run: npm ci

      - name: Instalar navegador Playwright
        run: npx playwright install --with-deps chromium

      - name: Ejecutar pruebas Web
        run: npm run test:web

      - name: Subir reporte Playwright
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/